### ISSUE TITLE
Extension doing nothing... ?

### ISSUE THREAD

**Issue by Julianoe** [mt-support/tribe-ext-maps-openstreetmap#4]
Even with extension activated, Leaflet extension installed, this extension does not do what it says it should..? Maybe a problem with classic views? How can we know ?

**Comment by cliffordp** [comment]
Hi, @Julianoe. That's a possibility, but we don't provide support/troubleshooting here. Please report your findings at https://support.theeventscalendar.com/, including your System Information if possible. Thank you.
